[package]
name = "oreak-protocol"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
jsonrpsee = { version = "0.26", features = ["client-core", "macros", "server-core"] }
oreak-core = { path = "../oreak-core" }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
